# -*- coding: utf-8 -*-
"""Projeto_Imobliliária_Pd_DEV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kGz805VxjWBZ0-83ZxoV4qdJkhO7CSJw

# Importando as informações
"""

import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'

dados = pd.read_csv(url, sep=';')

dados.head()

"""# Manipulando os dados"""

dados['Valor_por_mês'] = dados['Valor'] + dados['Condominio']

dados.head()

dados['Valor_por_ano'] = dados['Valor_por_mês'] * 12 + dados['IPTU']

dados.head()

dados['Descrição'] = dados['Tipo'] + ' em ' + dados['Bairro']
dados.head()

dados['Descrição'] = dados['Tipo'] + ' em ' + dados['Bairro'] + ' com ' + dados['Quartos'].astype(str) + ' quarto(s) ' + \
                     ' e ' + dados['Vagas'].astype(str) + ' vaga(s) de garagem.'
dados.head()

dados['Possui_suite'] = dados['Suites'].apply(lambda x: 'Sim' if x > 0 else 'Não')

dados.head()

"""# Salvando o arquivo"""

dados.to_csv('dados_dev.csv', index=False, sep=';')

pd.read_csv('dados_dev.csv', sep=';')

